[jobs.email-scheduler]
schedule = "*/5 * * * *"
command = "curl -X GET https://web-production-38df.up.railway.app/api/cron/send-scheduled-emails"

[jobs.sms-scheduler]
schedule = "*/5 * * * *"
command = "curl -X GET https://web-production-38df.up.railway.app/api/cron/send-scheduled-sms"