import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster 
          position="top-center"
          reverseOrder={false}
          gutter={8}
          toastOptions={{
            duration: 3000,
            style: {
              background: '#363636',
              color: '#fff',
              padding: '16px',
              borderRadius: '8px',
            },
            success: {
              duration: 3000,
              style: {
                background: '#4caf50',
                color: '#fff',
              },
            },
            error: {
              duration: 3000,
              style: {
                background: '#f44336',
                color: '#fff',
              },
            },
          }}
        />
        <main className="container-fluid min-vh-100 bg-light">
          {children}
        </main>
      </body>
    </html>
  )
}
