name: Scheduled Email Sending

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Email Sending API
        run: |
          echo "Calling email API endpoint..."
          response=$(curl -s -w "\n%{http_code}" "https://notification-system-f4dg.vercel.app/api/cron/send-scheduled-emails")
          status_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | sed '$d')

          echo "Status code: $status_code"
          echo "Response: $response_body"

          if [ "$status_code" -ne 200 ]; then
            echo "Error: API call failed with status $status_code"
            exit 1
          fi

          echo "API call successful"
